%% Training
trainOpts = rlTrainingOptions(...
    'MaxEpisodes', 5000, ...
    'MaxStepsPerEpisode', 200, ... % orig era 1000
    'ScoreAveragingWindowLength', 50, ...
    'StopTrainingCriteria', 'AverageReward', ...
    'StopTrainingValue', 800, ... % Determine this based on your reward scaling
    'SaveAgentCriteria', 'EpisodeReward', ...
    'SaveAgentValue', 800 ...
);
trainOpts.UseParallel = true;
trainOpts.ParallelizationOptions.Mode = "async";

%env.UseFastRestart = 'on';

%load('deen_network.mat', 'deen_net');

trainStats = train(agent, env, trainOpts);

