%% Training
trainOpts = rlTrainingOptions(...
    'MaxEpisodes', 5000, ...
    'MaxStepsPerEpisode', 1000, ...
    'ScoreAveragingWindowLength', 50, ...
    'StopTrainingCriteria', 'AverageReward', ...
    'StopTrainingValue', 800, ... % Determine this based on your reward scaling
    'SaveAgentCriteria', 'EpisodeReward', ...
    'SaveAgentValue', 800);

trainStats = train(agent, env, trainOpts);